### ISSUE TITLE
gulp-vulcanize does not run, vulcanize does

### ISSUE THREAD

**Issue by phreaknation** [sindresorhus/gulp-vulcanize#26]
Using the new Polymer 1.0 gulp-vulcanize loads but does not complete. However, vulcanize stand alone does.

code:
```
    gulp.task('vulc', function () {
      return gulp.src('./test-ui/window.html')
        .pipe(vulcanize({
          abspath: '',
          excludes: [],
          stripExcludes: false
        }))
        .pipe(rte('build:ext'))
        .pipe(gulp.dest('./test-ui/'));
    });
```

output:
>gulp vulc
[10:30:19] Using gulpfile .\gulpfile.js
[10:30:19] Starting 'vulc'...
{does not continue}

**Comment by Cammisuli** [comment]
On windows, setting the plugin to include inlineCss (inlineCss: true) does not complete the task. Leaving inlineCss false or excluding it allows the task to continue and vulcanize properly.

**Comment by sindresorhus** [comment]
https://github.com/Polymer/vulcanize/issues/new
