### ISSUE TITLE
"No resolver found" error on Windows

### ISSUE THREAD

**Issue by wq9** [sindresorhus/gulp-vulcanize#27]
When using gulp-vulcanize on Windows, [file.path](https://github.com/sindresorhus/gulp-vulcanize/blob/master/index.js#L23) is an absolute path like "C:\web\...". This results in "no resolver found" error and prevents vulcanize from working correctly.

See PolymerElements/polymer-starter-kit/issues/62

**Comment by sindresorhus** [comment]
This task just [passes the file path to `vulcanize`](https://github.com/sindresorhus/gulp-vulcanize/blob/47b924c1a4307edacd057dc356663eefaceca9a6/index.js#L23). It's up to `vulcanize` to handle the path correctly.

Open an issue on `vulcanize`: https://github.com/Polymer/vulcanize/issues/new
