### ISSUE TITLE
gulp-vulcanize not working in gulp but works in global (command line)

### ISSUE THREAD

**Issue by wizztjh** [sindresorhus/gulp-vulcanize#32]
gulp-vulcanize generated this

``` html
<html><head><meta charset="UTF-8"></head><body></body></html>
```

I did not receive any error

when I run the command in  command line `vulcanize dist/mr-ml.local.html`. It works correctly.

`gulp.js`
``` javascript
gulp.task('html', ['copy','js'], function () {
  gulp.src('dist/mr-ml.local.html')
    .pipe($.vulcanize({
      abspath: '',
      excludes: [],
      stripExcludes: false
    }))
    .pipe($.rename('mr-ml.html'))
    .pipe(gulp.dest('dist'))
    .on("error", function (err) { console.log("Error: " + err.message); })
})
```

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the `Vulcanize` [issue tracker](https://github.com/Polymer/vulcanize/issues).*

-

It working through the command-line, doesn't mean it's something wrong with this plugin. The vulcanize API doesn't work exactly like its CLI.

**Comment by rgbkrk** [comment]
Yuck. I'm getting the same issue. Sadly I'm just getting started with using gulp and vulcanize, so I'm a bit stuck on figuring this out. :unamused: 

Sorry to post on it @sindresorhus, I'm not even sure what would be a reasonable statement of the issue on the Vulcanize issue tracker. I appreciate *all* of your work and packages across the ecosystem, so thank you!

**Comment by wizztjh** [comment]
Hi Kyle,
For me, the problem occur because of gulp runs the task async. I use
run-sequence and returns the pipe of all the task to fix this.

https://github.com/wizztjh/metaroom-markup/blob/master/gulpfile.js#L28

**Comment by rgbkrk** [comment]
Reported as https://github.com/Polymer/vulcanize/issues/215
