### ISSUE TITLE
Gulp vulcanize should give a helpful error if "exclude" present rather than "excludes"

### ISSUE THREAD

**Issue by danmane** [sindresorhus/gulp-vulcanize#34]
It's easy to transition from CLI usage to gulp usage for gulp-vulcanize and miss that the command line flag is renamed from "exclude" to "excludes". Then it fails silently. It would be nice to have a helpful warning in this case.

**Comment by sindresorhus** [comment]
Open an issue on Vulcanize about it. This task is just a thin wrapper around their API.
