### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by adben** [sindresorhus/gulp-vulcanize#35]
There is a way to debug the vulcanization task? I'm getting no feedback, and there is no elements at the distribution, my project is based on polymer-starter-kit

```
...
[23:45:39] html all files 90.01 kB
[23:45:39] Finished 'html' after 2.85 s
[23:45:39] Starting 'vulcanize'...
```

**Comment by sindresorhus** [comment]
You would have to ask on https://github.com/Polymer/vulcanize Nothing like that is exposed in the API: https://github.com/Polymer/vulcanize#using-vulcanize-programmatically

Errors are handled correctly: https://github.com/sindresorhus/gulp-vulcanize/blob/c904004893c394bcdb2c3e5fb61c4745210cbf43/index.js#L22

Ensure you're returning the `gulp.src` stream.
