### ISSUE TITLE
Update version constraint for vulcanize 

### ISSUE THREAD

**Issue by justinfagnani** [sindresorhus/gulp-vulcanize#36]
vulcanize 1.14.7 includes a fix for inlining Firebase's minimized JS. gulp-vulcanize should already be picking it up for fresh installs, but there are reports that it's not. Can you update the constraint?

**Comment by sindresorhus** [comment]
The constraint are already loose enough: https://github.com/sindresorhus/gulp-vulcanize/blob/c904004893c394bcdb2c3e5fb61c4745210cbf43/package.json#L37

https://nodesource.com/blog/semver-tilde-and-caret
