### ISSUE TITLE
Not possible to vulcanize from a stream

### ISSUE THREAD

**Issue by panuhorsmalahti** [sindresorhus/gulp-vulcanize#40]
It would be useful (and be according to gulp best practices) if gulp-vulcanize could be supplied the `target.html` file and all the files required for vulcanization (the `target.html` would need to be specified as an option to gulp-vulcanize or vulcanize). As far as I understand, vulcanize itself will read the files it needs from the hard drive, so this feature might need some support from vulcanize too.

The task would then look like this:

```
gulp.task('default', () =>
    gulp.src('src/**/*')
        .pipe(vulcanize({
            target: 'src/index.html',
            abspath: '',
            excludes: [],
            stripExcludes: false
        }))
        .pipe(gulp.dest('dest'))
);
```

As it stands I need to compile all my .pug files to .html, my TypeScript files to .js, write them to the hard drive, vulcanize the files and then delete the extra files. This use of I/O causes a slower build time etc.

**Comment by sindresorhus** [comment]
As you said, this would need to be added to Vulcanize first.

**Comment by sindresorhus** [comment]
Open an issue/PR on Vulcanize and comment the link here.
